kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: teeworlds-deathmatch-2
  labels:
    app: teeworlds-deathmatch-2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: teeworlds-deathmatch-2
    spec:
      containers:
      - name: teeworlds-deathmatch-2
        image: riftbit/teeworlds:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8303
        env:
          - name: TW_sv_name
            value: "NPF - Teeworlds Deathmatch 2"
          - name: TW_sv_register
            value: "0"
          - name: TW_sv_gametype
            value: "dm"
          - name: TW_sv_motd
            value: "Welcome to the NPF Teeworlds server. Have fun!"
          - name: TW_sv_maprotation
            value: "dm1 dm2 dm3 dm6 dm7 dm8 dm9"
        resources:
          requests:
            memory: "512Mi"
            cpu: "0.5"
---
kind: Service
apiVersion: v1
metadata:
  name: teeworlds-deathmatch-2
  labels:
    app: teeworlds-deathmatch-2
spec:
  selector:
    app: teeworlds-deathmatch-2
  ports:
    - name: game
      protocol: UDP
      port: 8303
      targetPort: 8303
